export const initialState = {
  tiles: [
    {
      id: 0,
      value: "",
      status: "none",
    },
    {
      id: 1,
      value: "",
      status: "none",
    },
    {
      id: 2,
      value: "",
      status: "none",
    },
    {
      id: 3,
      value: "",
      status: "none",
    },
    {
      id: 4,
      value: "",
      status: "none",
    },
    {
      id: 5,
      value: "",
      status: "none",
    },
    {
      id: 6,
      value: "",
      status: "none",
    },
    {
      id: 7,
      value: "",
      status: "none",
    },
    {
      id: 8,
      value: "",
      status: "none",
    },
    {
      id: 9,
      value: "",
      status: "none",
    },
    {
      id: 10,
      value: "",
      status: "none",
    },
    {
      id: 11,
      value: "",
      status: "none",
    },
    {
      id: 12,
      value: "",
      status: "none",
    },
    {
      id: 13,
      value: "",
      status: "none",
    },
    {
      id: 14,
      value: "",
      status: "none",
    },
    {
      id: 15,
      value: "",
      status: "none",
    },
    {
      id: 16,
      value: "",
      status: "none",
    },
    {
      id: 17,
      value: "",
      status: "none",
    },
    {
      id: 18,
      value: "",
      status: "none",
    },
    {
      id: 19,
      value: "",
      status: "none",
    },
    {
      id: 20,
      value: "",
      status: "none",
    },
    {
      id: 21,
      value: "",
      status: "none",
    },
    {
      id: 22,
      value: "",
      status: "none",
    },
    {
      id: 23,
      value: "",
      status: "none",
    },
    {
      id: 24,
      value: "",
      status: "none",
    },
    {
      id: 25,
      value: "",
      status: "none",
    },
    {
      id: 26,
      value: "",
      status: "none",
    },
    {
      id: 27,
      value: "",
      status: "none",
    },
    {
      id: 28,
      value: "",
      status: "none",
    },
    {
      id: 29,
      value: "",
      status: "none",
    },
  ],
  keyboard: {
    row1: [
      { key: "q", status: "none" },
      { key: "w", status: "none" },
      { key: "e", status: "none" },
      { key: "r", status: "none" },
      { key: "t", status: "none" },
      { key: "y", status: "none" },
      { key: "u", status: "none" },
      { key: "i", status: "none" },
      { key: "o", status: "none" },
      { key: "p", status: "none" },
    ],
    row2: [
      { key: "a", status: "none" },
      { key: "s", status: "none" },
      { key: "d", status: "none" },
      { key: "f", status: "none" },
      { key: "g", status: "none" },
      { key: "h", status: "none" },
      { key: "j", status: "none" },
      { key: "k", status: "none" },
      { key: "l", status: "none" },
    ],
    row3: [
      { key: "enter", status: "N/A" },
      { key: "z", status: "none" },
      { key: "x", status: "none" },
      { key: "c", status: "none" },
      { key: "v", status: "none" },
      { key: "b", status: "none" },
      { key: "n", status: "none" },
      { key: "m", status: "none" },
      { key: "delete", status: "N/A" },
    ],
  },
  disableInteraction: false,
};
